apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd

spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: 'https://github.com/Al-HusseinHameedJasim/do-kubernetes-challenge'
    targetRevision: HEAD
    path: ./manifests

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-app

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.